annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: HAProxy Kubernetes Ingress Controller
  catalog.cattle.io/release-name: haproxy
apiVersion: v2
appVersion: 1.7.2
description: A Helm chart for HAProxy Kubernetes Ingress Controller
home: https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress
icon: https://raw.githubusercontent.com/haproxytech/helm-charts/main/kubernetes-ingress/chart-icon.png
keywords:
- ingress
- haproxy
kubeVersion: '>=1.17.0-0'
maintainers:
- email: mmhedhbi@haproxy.com
  name: Moemen Mhedhbi
- email: bassmann@haproxy.com
  name: Baptiste Assmann
- email: dkorunic@haproxy.com
  name: Dinko Korunic
name: haproxy
sources:
- https://github.com/haproxytech/kubernetes-ingress
type: application
version: 1.17.1000
