annotations:
  artifacthub.io/links: |
    - name: Homepage
      url: https://www.kubecost.com
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Kubecost
  catalog.cattle.io/release-name: kubecost
apiVersion: v2
appVersion: 1.89.1
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
icon: https://partner-charts.rancher.io/assets/logos/kubecost.png
name: cost-analyzer
version: 1.89.101
